name: Container Deployment to Vercel
on:
  push:
    branches: [main]
    paths:
      - "packages/container/**"


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install  


      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Login to Vercel
        run: vercel login --token ${{ secrets.VERCEL_TOKEN }}

      - name: Build container
        run: npm run build

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}